/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.ClubAthlete = factory(root.StravaApiV3.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ClubAthlete model module.
   * @module model/ClubAthlete
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>ClubAthlete</code>.
   * @alias module:model/ClubAthlete
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ClubAthlete</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClubAthlete} obj Optional instance to populate.
   * @return {module:model/ClubAthlete} The populated <code>ClubAthlete</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('resource_state'))
        obj.resourceState = ApiClient.convertToType(data['resource_state'], 'Number');
      if (data.hasOwnProperty('firstname'))
        obj.firstname = ApiClient.convertToType(data['firstname'], 'String');
      if (data.hasOwnProperty('lastname'))
        obj.lastname = ApiClient.convertToType(data['lastname'], 'String');
      if (data.hasOwnProperty('member'))
        obj.member = ApiClient.convertToType(data['member'], 'String');
      if (data.hasOwnProperty('admin'))
        obj.admin = ApiClient.convertToType(data['admin'], 'Boolean');
      if (data.hasOwnProperty('owner'))
        obj.owner = ApiClient.convertToType(data['owner'], 'Boolean');
    }
    return obj;
  }

  /**
   * Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\"
   * @member {Number} resourceState
   */
  exports.prototype.resourceState = undefined;

  /**
   * The athlete's first name.
   * @member {String} firstname
   */
  exports.prototype.firstname = undefined;

  /**
   * The athlete's last initial.
   * @member {String} lastname
   */
  exports.prototype.lastname = undefined;

  /**
   * The athlete's member status.
   * @member {String} member
   */
  exports.prototype.member = undefined;

  /**
   * Whether the athlete is a club admin.
   * @member {Boolean} admin
   */
  exports.prototype.admin = undefined;

  /**
   * Whether the athlete is club owner.
   * @member {Boolean} owner
   */
  exports.prototype.owner = undefined;


  return exports;

}));
